on: ["push", "pull_request"]

name: Test

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: uv sync --group lint

        - name: Run Ruff Linter
          run: uv run ruff check .

        - name: Run Ruff Formatter
          run: uv run ruff format --check .

        - name: Run mdformat
          run: uv run mdformat --check *.md docs/userguides/*.md

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: uv sync --group lint --group test

        - name: Run MyPy
          run: uv run mypy .

    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]   # eventually add `windows-latest`
                python-version: ["3.10", "3.11", "3.12", "3.13"]

        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - uses: actions/checkout@v6
          with:
            fetch-depth: 0

        - name: Install uv
          uses: astral-sh/setup-uv@v7
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Dependencies
          run: uv sync --group test

        - name: Run Tests
          run: uv run pytest -m "not fuzzing" -s --cov=ape_alchemy -n auto
          env:
            WEB3_ALCHEMY_PROJECT_ID: ${{ secrets.WEB3_ALCHEMY_PROJECT_ID }}
            # NOTE: For CI testing w/ Free Tier API, use more forgiving rate limit
            APE_ALCHEMY_RATE_LIMIT_MIN_RETRY_DELAY: 5000
            APE_ALCHEMY_RATE_LIMIT_MAX_RETRY_DELAY: 15000
            APE_ALCHEMY_RATE_LIMIT_MAX_RETRIES: 15

# NOTE: uncomment this block after you've marked tests with @pytest.mark.fuzzing
#    fuzzing:
#        runs-on: ubuntu-latest
#
#        strategy:
#            fail-fast: true
#
#        steps:
#        - uses: actions/checkout@v6
#
#        - name: Install uv
#          uses: astral-sh/setup-uv@v7
#          with:
#              python-version: "3.10"
#
#        - name: Install Dependencies
#          run: uv sync --group test
#
#        - name: Run Tests
#          run: uv run pytest -m "fuzzing" --no-cov -s
